/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as OauthGoogleCalendarReturnRouteImport } from './routes/oauth/google-calendar/return'
import { Route as ApiPublicEmailSummariesDispatchRouteImport } from './routes/api/public/email-summaries/dispatch'
import { Route as ApiPublicGoogleCalendarNotifyRouteImport } from './routes/api/public/google-calendar/notify'
import { Route as ApiPublicGoogleCalendarReconcileRouteImport } from './routes/api/public/google-calendar/reconcile'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleCalendarReturnRoute =
  OauthGoogleCalendarReturnRouteImport.update({
    id: '/oauth/google-calendar/return',
    path: '/oauth/google-calendar/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailSummariesDispatchRoute =
  ApiPublicEmailSummariesDispatchRouteImport.update({
    id: '/api/public/email-summaries/dispatch',
    path: '/api/public/email-summaries/dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarNotifyRoute =
  ApiPublicGoogleCalendarNotifyRouteImport.update({
    id: '/api/public/google-calendar/notify',
    path: '/api/public/google-calendar/notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarReconcileRoute =
  ApiPublicGoogleCalendarReconcileRouteImport.update({
    id: '/api/public/google-calendar/reconcile',
    path: '/api/public/google-calendar/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/today': typeof AuthenticatedTodayRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/email-summaries/dispatch': typeof ApiPublicEmailSummariesDispatchRoute
  '/api/public/google-calendar/notify': typeof ApiPublicGoogleCalendarNotifyRoute
  '/api/public/google-calendar/reconcile': typeof ApiPublicGoogleCalendarReconcileRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/today': typeof AuthenticatedTodayRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/email-summaries/dispatch': typeof ApiPublicEmailSummariesDispatchRoute
  '/api/public/google-calendar/notify': typeof ApiPublicGoogleCalendarNotifyRoute
  '/api/public/google-calendar/reconcile': typeof ApiPublicGoogleCalendarReconcileRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/google-calendar/return': typeof OauthGoogleCalendarReturnRoute
  '/api/public/email-summaries/dispatch': typeof ApiPublicEmailSummariesDispatchRoute
  '/api/public/google-calendar/notify': typeof ApiPublicGoogleCalendarNotifyRoute
  '/api/public/google-calendar/reconcile': typeof ApiPublicGoogleCalendarReconcileRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/activities'
    | '/calendar'
    | '/family'
    | '/onboarding'
    | '/today'
    | '/invite/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/email-summaries/dispatch'
    | '/api/public/google-calendar/notify'
    | '/api/public/google-calendar/reconcile'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/activities'
    | '/calendar'
    | '/family'
    | '/onboarding'
    | '/today'
    | '/invite/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/email-summaries/dispatch'
    | '/api/public/google-calendar/notify'
    | '/api/public/google-calendar/reconcile'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/activities'
    | '/_authenticated/calendar'
    | '/_authenticated/family'
    | '/_authenticated/onboarding'
    | '/_authenticated/today'
    | '/invite/$token'
    | '/oauth/google-calendar/return'
    | '/api/public/email-summaries/dispatch'
    | '/api/public/google-calendar/notify'
    | '/api/public/google-calendar/reconcile'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OauthGoogleCalendarReturnRoute: typeof OauthGoogleCalendarReturnRoute
  ApiPublicEmailSummariesDispatchRoute: typeof ApiPublicEmailSummariesDispatchRoute
  ApiPublicGoogleCalendarNotifyRoute: typeof ApiPublicGoogleCalendarNotifyRoute
  ApiPublicGoogleCalendarReconcileRoute: typeof ApiPublicGoogleCalendarReconcileRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google-calendar/return': {
      id: '/oauth/google-calendar/return'
      path: '/oauth/google-calendar/return'
      fullPath: '/oauth/google-calendar/return'
      preLoaderRoute: typeof OauthGoogleCalendarReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-summaries/dispatch': {
      id: '/api/public/email-summaries/dispatch'
      path: '/api/public/email-summaries/dispatch'
      fullPath: '/api/public/email-summaries/dispatch'
      preLoaderRoute: typeof ApiPublicEmailSummariesDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/notify': {
      id: '/api/public/google-calendar/notify'
      path: '/api/public/google-calendar/notify'
      fullPath: '/api/public/google-calendar/notify'
      preLoaderRoute: typeof ApiPublicGoogleCalendarNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/reconcile': {
      id: '/api/public/google-calendar/reconcile'
      path: '/api/public/google-calendar/reconcile'
      fullPath: '/api/public/google-calendar/reconcile'
      preLoaderRoute: typeof ApiPublicGoogleCalendarReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  OauthGoogleCalendarReturnRoute: OauthGoogleCalendarReturnRoute,
  ApiPublicEmailSummariesDispatchRoute: ApiPublicEmailSummariesDispatchRoute,
  ApiPublicGoogleCalendarNotifyRoute: ApiPublicGoogleCalendarNotifyRoute,
  ApiPublicGoogleCalendarReconcileRoute: ApiPublicGoogleCalendarReconcileRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
